version: '3.7'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esconfig:/usr/share/elasticsearch/config
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elknet

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elknet
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: logstash
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /opt/elastic/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elknet

volumes:
  esdata:
    driver: local
  esconfig:
    driver: local
  certs:
    driver: local

networks:
  elknet:
    driver: bridge
