version: '3.7'

services:

  es01:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: es01
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - esconfig01:/usr/share/elasticsearch/config
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/elasticsearch/config/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elknet

  es02:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: es02
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - esconfig02:/usr/share/elasticsearch/config
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/elasticsearch/config/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elknet

  es03:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: es03
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - esconfig03:/usr/share/elasticsearch/config
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/elasticsearch/config/es03.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elknet

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elknet

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: logstash
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /opt/elastic/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elknet

volumes:
  esdata01:
    driver: local
  esconfig01:
    driver: local
  esdata02:
    driver: local
  esconfig02:
    driver: local
  esdata03:
    driver: local
  esconfig03:
    driver: local
  certs:
    driver: local

networks:
  elknet:
    driver: bridge
