version: '3.7'

services:

  es01:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: es01
    environment:
      ES_JAVA_OPTS: "-Xms%ES_HEAP_SIZE%m -Xmx%ES_HEAP_SIZE%m"
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - esconfig01:/usr/share/elasticsearch/config
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/elasticsearch/config/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elknet

  elasticsearch:
    image: tianon/true
    restart: "no"
    depends_on: [ "es01" ]

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elknet

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: logstash
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /opt/elastic/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx%LS_HEAP_SIZE%m -Xms%LS_HEAP_SIZE%m"
    networks:
      - elknet

  elastalert:
    image: jertel/elastalert-docker
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/elastalert/elastalert.yaml:/opt/config/elastalert_config.yaml
      - /opt/elastic/elastalert/rules:/opt/rules
    networks:
      - elknet

  wazuh:
    image: wazuh/wazuh:3.13.1_7.8.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    networks:
      - elknet
    volumes:
      - wazuh_data:/var/ossec/data
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/filebeat-wazuh/filebeat.yml:/etc/filebeat/filebeat.yml
      - /opt/elastic/filebeat-wazuh/module/wazuh:/usr/share/filebeat/module/wazuh


volumes:
  esdata01:
    driver: local
  esconfig01:
    driver: local
  certs:
    driver: local
  wazuh_data:
    driver: local

networks:
  elknet:
    driver: bridge
