version: '3.7'

services:

  elastalert:
    image: jertel/elastalert-docker
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/elastalert/elastalert.yaml:/opt/config/elastalert_config.yaml
      - /opt/elastic/elastalert/rules:/opt/rules
    networks:
      - elknet

volumes:
  certs:
    driver: local

networks:
  elknet:
    driver: bridge
