version: '3.7'

services:

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - certs:/usr/share/elasticsearch/config/certificates
      - /opt/elastic/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elknet

volumes:
  certs:
    driver: local

networks:
  elknet:
    driver: bridge
